jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Archive build directory
      run: tar -czf build.tar.gz build

    - name: Copy tar.gz to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build.tar.gz"
        target: "/home/ec2-user/"

    - name: Extract and deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          rm -rf /home/ec2-user/deploy
          mkdir -p /home/ec2-user/deploy
          tar -xzf /home/ec2-user/build.tar.gz -C /home/ec2-user/deploy
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/ec2-user/deploy/build/. /var/www/html/
          sudo chmod -R o+rx /var/www/html/static
          sudo systemctl restart httpd
